import { setTimeout as delay } from "node:timers/promises";

import {
  captureScreen,
  captureWindow,
  clickDialogButton,
  clickElementByLabel,
  clickUiElement,
  clickSnapshotElement,
  click,
  dragSnapshotElement,
  drag,
  findUiElements,
  focusWindow,
  hotkey,
  launchApp,
  listApps,
  listDialogs,
  listMenuItems,
  listScreens,
  listWindows,
  clickMenuPath,
  moveWindow,
  moveMouse,
  pressKeys,
  quitApp,
  resizeWindow,
  scrollSnapshotElement,
  scroll,
  scrollElementByLabel,
  seeUi,
  setWindowBounds,
  setWindowState,
  switchApp,
  waitForUiElement,
  waitForWindow,
  typeText,
} from "../backend/tools.js";

export const defaultWorkflowActionHandlers = {
  sleep: async ({ durationMs = 1000 } = {}) => {
    await delay(durationMs);
    return { durationMs };
  },
  "windows.list": async () => await listWindows(),
  "screens.list": async () => await listScreens(),
  "window.focus": async (args) => await focusWindow(args ?? {}),
  "window.move": async (args) => await moveWindow(args ?? {}),
  "window.resize": async (args) => await resizeWindow(args ?? {}),
  "window.setBounds": async (args) => await setWindowBounds(args ?? {}),
  "window.state": async (args) => await setWindowState(args ?? {}),
  "window.capture": async (args) => await captureWindow(args ?? {}),
  "window.wait": async (args) => await waitForWindow(args ?? {}),
  "app.list": async () => await listApps(),
  "app.launch": async (args) => await launchApp(args ?? {}),
  "app.switch": async (args) => await switchApp(args ?? {}),
  "app.quit": async (args) => await quitApp(args ?? {}),
  "dialog.list": async (args) => await listDialogs(args ?? {}),
  "dialog.click": async (args) => await clickDialogButton(args ?? {}),
  "menu.list": async (args) => await listMenuItems(args ?? {}),
  "menu.click": async (args) => await clickMenuPath(args ?? {}),
  "screen.capture": async (args) => await captureScreen(args ?? {}),
  "mouse.move": async (args) => await moveMouse(args ?? {}),
  "mouse.click": async (args) => await click(args ?? {}),
  "mouse.drag": async (args) => await drag(args ?? {}),
  "element.click": async (args) => await clickElementByLabel(args ?? {}),
  "element.scroll": async (args) => await scrollElementByLabel(args ?? {}),
  scroll: async (args) => await scroll(args ?? {}),
  see: async (args) => await seeUi(args ?? {}),
  "snapshot.click": async (args) => await clickSnapshotElement(args ?? {}),
  "snapshot.scroll": async (args) => await scrollSnapshotElement(args ?? {}),
  "snapshot.drag": async (args) => await dragSnapshotElement(args ?? {}),
  "ui.find": async (args) => await findUiElements(args ?? {}),
  "ui.click": async (args) => await clickUiElement(args ?? {}),
  "ui.wait": async (args) => await waitForUiElement(args ?? {}),
  hotkey: async (args) => await hotkey(args ?? {}),
  type: async (args) => await typeText(args ?? {}),
  press: async (args) => await pressKeys(args ?? {}),
};
